server:
  port: 8001

spring:
  application:
    name: userService8001

  datasource:
    url: jdbc:mysql://47.98.150.138:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 89NoLi10
    dbcp2:
      max-idle: 5
      min-idle: 2
      initial-size: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: vvy.springcloud.entity #所有entity别名类所在的包